name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Updated to v4

      - name: Use Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '20'

      - name: Build plugin
        run: |
          npm ci
          npm run build --if-present

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -f "release-notes.md" ]; then
            echo "Changes in this release" > release-notes.md
          fi
          
          tag="${{ github.ref_name }}"

          gh release create "$tag" \
            --title="$tag" \
            --notes-file="release-notes.md" \
            main.js manifest.json styles.css
